apiVersion: v1
kind: Pod
metadata:
  name: inference-driver
  labels:
    app: inference-driver
spec:
  restartPolicy: Never

  hostIPC: true

  volumes:
    # Just to run code inside the container
    - name: workdir
      hostPath:
        path: /data/osh_demo
        type: Directory

    # Share the socket directory with the host camera process
    - name: host-tmp
      hostPath:
        path: /tmp
        type: Directory

  containers:
  - name: demo
    image: ghcr.io/snu-rtos/osh-compile:latest
    imagePullPolicy: Always
    command: ["sleep"]
    args: ["infinity"]

    securityContext:
      runAsUser: 0
      seccompProfile:
        type: Unconfined

    volumeMounts:
    - name: workdir
      mountPath: /work
    - name: host-tmp
      mountPath: /tmp

    resources:
      requests:
        hailo.ai/npu: 8
      limits:
        hailo.ai/npu: 8

    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

  nodeSelector:
    # Enable this only if you want to force scheduling to a specific node
    # kubernetes.io/hostname: your-node-name
