apiVersion: npu.snu-rtos.io/v1alpha1
kind: NPUTask
metadata: {name: exclusive-a}
spec:
  image: npu-share-client:local
  command: [/usr/local/bin/shared_runner]
  args: [--hef, $(MODEL_PATH), --runs, "500"]
  model: {path: /opt/models/yolov10s.hef, key: yolov10s}
  npuCount: 1
  mode: Batch
  suspend: true
---
apiVersion: npu.snu-rtos.io/v1alpha1
kind: NPUTask
metadata: {name: exclusive-b}
spec:
  image: npu-share-client:local
  command: [/usr/local/bin/shared_runner]
  args: [--hef, $(MODEL_PATH), --runs, "500"]
  model: {path: /opt/models/tiny_yolov4.hef, key: tiny-yolov4}
  npuCount: 1
  mode: Batch
  suspend: true
---
apiVersion: npu.snu-rtos.io/v1alpha1
kind: NPUTask
metadata: {name: exclusive-c}
spec:
  image: npu-share-client:local
  command: [/usr/local/bin/shared_runner]
  args: [--hef, $(MODEL_PATH), --runs, "500"]
  model: {path: /opt/models/yolov10s.hef, key: yolov10s}
  npuCount: 1
  mode: Batch
  suspend: true
---
apiVersion: npu.snu-rtos.io/v1alpha1
kind: NPUTask
metadata: {name: exclusive-d}
spec:
  image: npu-share-client:local
  command: [/usr/local/bin/shared_runner]
  args: [--hef, $(MODEL_PATH), --runs, "500"]
  model: {path: /opt/models/tiny_yolov4.hef, key: tiny-yolov4}
  npuCount: 1
  mode: Batch
  suspend: true
